apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: exercise3

spec:
  replicas: 3

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
      - name: payment-service
        image: poobesh1/payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80